name: Greetings

on:
  pull_request_review:
    types: [submitted]

jobs:
  greeting:
    if: github.event.review.state == 'approved'    
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!    
        
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Message that will be displayed on users first issue'
          pr-message: 'Message that will be displayed on users first pull request'
