name: Verify that PR reviewer checklist has been filled out for PRs to main

on:
  pull_request:
    branches:
      - main
      
jobs:
  verify-checklist-completed:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(comments);
            let reviewerSignedOff = false;
            for (const comment of comments.data) {
              const body = comment.body.trim();
              if (body.includes('- [x] PR Reviewer')) {
                reviewerSignedOff = true;
              } else if (body.includes('- [ ] PR Reviewer')) {
                reviewerSignedOff = false;
              }
              console.log(comment.body.trim());
              console.log({reviewerSignedOff});
            }
            if (reviewerSignedOff) {
              console.log('passing, reviewer did sign off');
            } else {
              throw new Error("PR reviewer did not sign off!");
            }
