name: Verify that PR reviewer checklist has been filled out for PRs to main

on:
  pull_request:
    branches:
      - main
  issue_comment:
    types: [created, edited, deleted]
# NOTE(bowei): issue_comment gets triggered from "default" scope, not pull request scope,
# so we have to do some hacky stuff to get the PR check to pass when triggered by a PR reviewer editing their checklist
# see: 
# https://docs.github.com/en/rest/reference/actions?query=retry#list-workflow-runs
# https://docs.github.com/en/rest/reference/actions?query=retry#re-run-a-workflow
# https://octokit.github.io/rest.js/v18#actions-list-workflow-runs
# https://github.com/actions/github-script
# https://stackoverflow.com/questions/56435547/how-do-i-re-run-github-actions
# https://pakstech.com/blog/gh-actions-issue-comments/
# https://github.community/t/trigger-action-via-pull-request-message/17630
# https://blog.ksoichiro.com/post/2021/03/comment-on-pr-when-approved/
# https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
# https://github.com/actions/checkout/issues/331
# https://github.community/t/on-issue-comment-events-are-not-triggering-workflows/16784/9
# https://github.com/TeamAmaze/AmazeFileManager/blob/master/.github/workflows/android-debug-artifact-ondemand.yml
# https://github.com/adrianjost/workflow-trigger-comment-example/blob/master/.github/workflows/demo.yml
# https://stackoverflow.com/questions/59518627/github-action-for-issue-comment-doesnt-shown-in-checks-for-pr <- this one
# https://github.community/t/github-actions-as-status-checks/16666/16 <- also
# https://sanderknape.com/2020/05/deploy-pull-requests-github-actions-deployments/
# https://github.com/Khan/pull-request-comment-trigger
# https://github.com/marketplace/actions/pull-request-comment-branch
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_call
# 
# 
      
jobs:
  verify-checklist-completed:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            console.log(github.rest.actions.retryWorkflow);
            const workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pr-reviewer-checklist-verify.yml'
            }).data.workflow_runs;
            console.log({workflowRuns});
            
            /* await github.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
            }); */ ;
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(comments);
            let reviewerSignedOff = false;
            for (const comment of comments.data) {
              const body = comment.body.trim();
              if (body.includes('- [x] PR Reviewer')) {
                reviewerSignedOff = true;
              } else if (body.includes('- [ ] PR Reviewer')) {
                reviewerSignedOff = false;
              }
              console.log(comment.body.trim());
              console.log({reviewerSignedOff});
            }
            if (reviewerSignedOff) {
              console.log('passing, reviewer did sign off');
            } else {
              throw new Error("PR reviewer did not sign off!");
            }
